apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: http-server
  name: http-server
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/http-server
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      run: http-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: http-server
    spec:
      containers:
      - image: simpleserver:0.5
        imagePullPolicy: Never
        name: http-server
        ports:
        - containerPort: 9000
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            memory: "800Mi"
            cpu: "0.2"
          limits:
            memory: "1200Mi"
            cpu: "0.4"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
